### ISSUE TITLE
Updated Pressure Drop Calculation

### ISSUE THREAD

**Issue by PoggeyWinter** [Jerell/fams#11]
**Is your feature request related to a problem? Please describe.**
Previous pressure drop calculation given was too simplified

**Describe the solution you'd like**
The following pressure drop calculation relies on less assumptions for gas phase flow so should give a more accurate output.

**Context**
For reference here is the initial equation before rearrangement:
w^2=[(D*A^2)/(v*f*L)]-[(P1^2-P2^2)/P1)
The rearrangement for P2 is as such:
P2=((√P1)*√((A^2*D*P)-(f*L*v*w^2)))/A√D
(I can provide the non type text versions of these equations if that is clearer)

The terms for this equation are:
w= Mass flowrate [kg/s] (user input)
D= Diameter of pipe [m] (model definition)
A= Cross Sectional Area [m^2] (model definition)
v= Specific Volume [m^3/kg] (v=1/density)
f= Friction Factor (calculated, see below)
L= Pipe Length [m] (model definition)
P1= Initial Pressure [Pa] (user input)
P2= Final Pressure [Pa] (equation output)

The friction factor is dependent on the type of flow in the pipeline, this can be defined using Reynolds number:
Re=(ρ*u*D)/μ

Re= Reynolds Number (equation output)
ρ= Density [kg/m^3] (calculated)
u= Velocity [m/s] 
D= Diameter of pipe [m]
μ= Dynamic Viscosity [Pa.s]

Based on the value of Reynolds numbers one of two equations will be used for calculating friction factor.

If Re<2000 (Laminar) then use the following equation:
f=64/Re

f= Friction Factor
Re= Reynolds number

If Re>2000 (Transient/Turbulent) then use the following equation (Weymouth):
f=0.094/((D*1000)^1/3

f= Friction Factor
D= Diameter [m]

Notes on accuracy:
- 2000<Re<4000 is when the fluid is transient, within this range the Weymouth friction factor will lose accuracy the closer to Re=2000.
- Weymouth friction factors are most accurate in a 20-inch pipeline. The factor will be greater than Moody chart factors for sizes less than 20-inch, and smaller for sizes larger than 20-inch.

Assumptions that are taken for the basis on this formula:
1. Isothermal flow.
2. No mechanical work is done on or by the system.
3. Steady flow or discharge unchanged with time.
4. The gas obeys the perfect gas laws.
5. The velocity may be represented by the average velocity at a cross section.
6. The friction factor is constant along the pipe.
7. The pipe line is straight and horizontal between end points.
8. Acceleration can be neglected because the pipe line is long (This is equivalent to the complete· isothermal equation if the pipe line is long and also for shorter lines if the ratio of pressure drop to initial pressure is small.)

**Comment by Jerell** [comment]
Can you tell me where `u` comes from? We don't have an object with a velocity property.

![image](https://user-images.githubusercontent.com/6231064/124459866-8ca65800-dd86-11eb-96ae-837bfcbba3d6.png)

Also I need to set up tests like the one shown below, so can you give me maybe two sets of input values and the calculated value for each one?

![image](https://user-images.githubusercontent.com/6231064/124458797-53b9b380-dd85-11eb-8e15-f256320f8546.png)

**Comment by PoggeyWinter** [comment]
Here is the calculation for velocity [m/s]:

u=  w/(A*ρ)

w=  Mass flowrate [kg/s] (user input)
A= Cross Sectional Area [m^2] (model definition)
ρ= Density [kg/m^3] (calculated)

In terms of test cases I can take a look at those today, I will then get back to you with the input conditions and the outputs I get

**Comment by PoggeyWinter** [comment]
So, I have done some test cases with the equation on my side:
1. Length= 200 [m], Diameter= 0.9144 [m]
Mass flowrate = 150 [ks/s], Initial pressure= 100000 [Pa], Initial Temperature= 300 [K],
Final Pressure = 98997.3989873648 Pa

2. Length= 200 [m], Diameter= 0.9144 [m]
Mass flowrate = 100 [ks/s], Initial pressure= 300000 [Pa], Initial Temperature= 350 [K],
Final Pressure = 299827.530058575 Pa

3. Length= 200 [m], Diameter= 0.9144 [m]
Mass flowrate = 200 [ks/s], Initial pressure= 10000000 [Pa], Initial Temperature= 300 [K],
Final Pressure = 9999982.26531816 Pa

A note as well, I think a previous number I gave for the viscosity calculation needs to be updated. 
Previously Ref viscosity = 0.018 cp, this needs to be changed to 0.000018 Pa.s. So the number has been divided by 1000 to update the units from cp to Pa.s (which is how it needs to be used in the equation for Reynolds number)
